# Site settings
name: Dirk Lawhon
title: Dirk Lawhon | Software Engineer
description: The future ain't what it used to be.
email: dirklawhon@protonmail.com
baseurl: ""
url: http://dirklawhon.com
cover: http://dirklawhon.com/img/cover.jpg
social:
  title: email
  url: mailto:dirklawhon@protonmail.com
  title: github
  url: https://github.com/dirklawhon
  title: linkedin
  url: https://www.linkedin.com/in/dirklawhon

# Build settings
markdown: kramdown
